import { useEffect, useId, useRef, type ReactNode, type ButtonHTMLAttributes } from 'react';
import styles from '../styles/app.module.css';
export function Button({ variant = 'primary', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' }) { return <button {...props} className={`${styles.button} ${styles[variant]}`} />; }
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className={styles.field}><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
const states: Record<string, [string, string]> = { SCHEDULED: ['Agendada', 'info'], PENDING: ['Pendente', 'warning'], EXPIRED: ['Confirmação encerrada', 'warning'], CONFIRMED: ['Confirmada', 'success'], CANCELLED: ['Cancelada', 'danger'], ATTENDED: ['Realizada', 'success'], ABSENT: ['Falta · pode justificar', 'danger'], EXCUSED: ['Falta abonada', 'success'], APPROVED: ['Aprovado', 'success'], REJECTED: ['Rejeitado', 'danger'], PROVISIONAL: ['Prazo de justificativa', 'warning'], CONSOLIDATED: ['Não justificada', 'danger'], QUARANTINED: ['Verificação pendente', 'info'], CLEAN: ['Arquivo verificado', 'success'], PURGED: ['Retenção encerrada', 'muted'], BLOCKED: ['Bloqueado', 'muted'], FREE: ['Vago', 'muted'] };
export function Badge({ state }: { state: string }) { const [text, color] = states[state] ?? [state, 'info']; return <span className={`${styles.badge} ${styles[color]}`}>{text}</span>; }
export function Message({ children, error = false }: { children: ReactNode; error?: boolean }) { return <div className={`${styles.message} ${error ? styles.danger : styles.info}`} role={error ? 'alert' : 'status'}>{children}</div>; }
export function Loading() { return <div aria-busy="true"><Message>Carregando suas informações…</Message><div className={styles.skeleton} /></div>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { const ref = useRef<HTMLDialogElement>(null), id = useId(); useEffect(() => { const dialog = ref.current!, trigger = document.activeElement; dialog.showModal(); return () => { dialog.close(); if (trigger instanceof HTMLElement && trigger.isConnected) trigger.focus(); }; }, []); return <dialog ref={ref} className={styles.modal} aria-labelledby={id} onCancel={onClose}><div className={styles.row}><h2 id={id}>{title}</h2><Button variant="secondary" onClick={onClose} aria-label="Fechar diálogo">Fechar</Button></div>{children}</dialog>; }
